In [1]:
#needed to make web requests

import requests

In [2]:
#store the data we get as a dataframe

import pandas as pd

In [3]:
#convert the response as a strcuctured json

import json

In [4]:
#mathematical operations on lists

import numpy as np

In [5]:
#parse the datetimes we get from NOAA

from datetime import datetime

In [6]:
# File to Load (Remember to Change These)

weather_data_to_load = "Resources/historical_data_by_month.csv"

weather_data = pd.read_csv(weather_data_to_load)

weather_data["NAME"].unique()

array(['SEATTLE TACOMA AIRPORT, WA US',
       'FORT LAUDERDALE INTERNATIONAL AIRPORT, FL US',
       'LONG BEACH DAUGHERTY AIRPORT, CA US',
       'MCCARRAN INTERNATIONAL AIRPORT, NV US',
       'LAGUARDIA AIRPORT, NY US',
       'NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US',
       'ORLANDO SANFORD AIRPORT, FL US', 'DAL FTW WSCMO AIRPORT, TX US',
       'BALTIMORE WASHINGTON INTERNATIONAL AIRPORT, MD US',
       'WASHINGTON REAGAN NATIONAL AIRPORT, VA US',
       'DALLAS FAA AIRPORT, TX US',
       'LOS ANGELES INTERNATIONAL AIRPORT, CA US',
       'EVERETT SNOHOMISH CO AIRPORT, WA US',
       'SANTA ANA JOHN WAYNE AIRPORT, CA US',
       'MIAMI INTERNATIONAL AIRPORT, FL US',
       'ORLANDO INTERNATIONAL AIRPORT, FL US', 'BOSTON, MA US',
       'SAN FRANCISCO INTERNATIONAL AIRPORT, CA US',
       'CHICAGO MIDWAY AIRPORT, IL US',
       'ONTARIO INTERNATIONAL AIRPORT, CA US',
       'WASHINGTON DULLES INTERNATIONAL AIRPORT, VA US',
       'PROVIDENCE, RI US', 'JFK INTERNATIONAL AIRPORT, NY US',
       'ATLANTA HARTSFIELD JACKSON INTERNATIONAL AIRPORT, GA US',
       'CHICAGO OHARE INTERNATIONAL AIRPORT, IL US'], dtype=object)

In [7]:
#View Dataframe

weather_data.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,PRCP,SNOW,TAVG,TMAX,TMIN,WDF5,WSF5
0,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-01,7.8,4.99,2.8,41.8,46.2,37.3,200.0,40.0
1,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-02,8.7,3.06,2.0,39.3,45.0,33.5,200.0,46.0
2,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-03,9.8,6.29,0.0,45.2,51.4,38.9,200.0,55.0
3,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-04,8.5,4.47,0.0,45.5,52.2,38.8,160.0,36.0
4,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-05,7.2,3.20,0.0,52.3,59.7,44.9,220.0,32.0

In [8]:
#Splitting 'Name' Column into columns: 'Airport' and 'LOCATION'

weather_data = weather_data[["NAME", "LATITUDE", "LONGITUDE", "ELEVATION", "DATE", "AWND", "WSF5", "PRCP", "SNOW",
                            "TAVG", "TMAX", "TMIN"]]
weather_data[["AIRPORT", "LOCATION"]] = weather_data["NAME"].str.split(",", expand=True)
weather_data

,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,WSF5,PRCP,SNOW,TAVG,TMAX,TMIN,AIRPORT,LOCATION
0,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-01,7.8,40.0,4.99,2.8,41.8,46.2,37.3,SEATTLE TACOMA AIRPORT,WA US
1,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-02,8.7,46.0,3.06,2.0,39.3,45.0,33.5,SEATTLE TACOMA AIRPORT,WA US
2,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-03,9.8,55.0,6.29,0.0,45.2,51.4,38.9,SEATTLE TACOMA AIRPORT,WA US
3,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-04,8.5,36.0,4.47,0.0,45.5,52.2,38.8,SEATTLE TACOMA AIRPORT,WA US
4,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-05,7.2,32.0,3.20,0.0,52.3,59.7,44.9,SEATTLE TACOMA AIRPORT,WA US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",41.96017,-87.93164,204.8,2022-02,11.9,47.0,2.59,12.9,27.5,35.3,19.7,CHICAGO OHARE INTERNATIONAL AIRPORT,IL US
3464,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",41.96017,-87.93164,204.8,2022-03,10.5,66.0,3.69,3.8,40.7,49.1,32.4,CHICAGO OHARE INTERNATIONAL AIRPORT,IL US
3465,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",41.96017,-87.93164,204.8,2022-04,11.2,59.0,5.31,0.4,47.0,55.1,38.9,CHICAGO OHARE INTERNATIONAL AIRPORT,IL US
3466,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",41.96017,-87.93164,204.8,2022-05,10.7,43.0,3.48,0.0,63.7,72.2,55.2,CHICAGO OHARE INTERNATIONAL AIRPORT,IL US
3467,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",41.96017,-87.93164,204.8,2022-06,8.5,84.0,2.67,0.0,72.2,82.6,61.8,CHICAGO OHARE INTERNATIONAL AIRPORT,IL US

In [9]:

weather_data["NAME"].unique()

array(['SEATTLE TACOMA AIRPORT, WA US',
       'FORT LAUDERDALE INTERNATIONAL AIRPORT, FL US',
       'LONG BEACH DAUGHERTY AIRPORT, CA US',
       'MCCARRAN INTERNATIONAL AIRPORT, NV US',
       'LAGUARDIA AIRPORT, NY US',
       'NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US',
       'ORLANDO SANFORD AIRPORT, FL US', 'DAL FTW WSCMO AIRPORT, TX US',
       'BALTIMORE WASHINGTON INTERNATIONAL AIRPORT, MD US',
       'WASHINGTON REAGAN NATIONAL AIRPORT, VA US',
       'DALLAS FAA AIRPORT, TX US',
       'LOS ANGELES INTERNATIONAL AIRPORT, CA US',
       'EVERETT SNOHOMISH CO AIRPORT, WA US',
       'SANTA ANA JOHN WAYNE AIRPORT, CA US',
       'MIAMI INTERNATIONAL AIRPORT, FL US',
       'ORLANDO INTERNATIONAL AIRPORT, FL US', 'BOSTON, MA US',
       'SAN FRANCISCO INTERNATIONAL AIRPORT, CA US',
       'CHICAGO MIDWAY AIRPORT, IL US',
       'ONTARIO INTERNATIONAL AIRPORT, CA US',
       'WASHINGTON DULLES INTERNATIONAL AIRPORT, VA US',
       'PROVIDENCE, RI US', 'JFK INTERNATIONAL AIRPORT, NY US',
       'ATLANTA HARTSFIELD JACKSON INTERNATIONAL AIRPORT, GA US',
       'CHICAGO OHARE INTERNATIONAL AIRPORT, IL US'], dtype=object)

In [10]:
weather_data["AIRPORT"] = weather_data["NAME"].str.split(",")
weather_data.head()

,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,WSF5,PRCP,SNOW,TAVG,TMAX,TMIN,AIRPORT,LOCATION
0,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-01,7.8,40.0,4.99,2.8,41.8,46.2,37.3,"[SEATTLE TACOMA AIRPORT, WA US]",WA US
1,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-02,8.7,46.0,3.06,2.0,39.3,45.0,33.5,"[SEATTLE TACOMA AIRPORT, WA US]",WA US
2,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-03,9.8,55.0,6.29,0.0,45.2,51.4,38.9,"[SEATTLE TACOMA AIRPORT, WA US]",WA US
3,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-04,8.5,36.0,4.47,0.0,45.5,52.2,38.8,"[SEATTLE TACOMA AIRPORT, WA US]",WA US
4,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-05,7.2,32.0,3.20,0.0,52.3,59.7,44.9,"[SEATTLE TACOMA AIRPORT, WA US]",WA US

In [11]:
#Remove State from 'Airport' Column

weather_data["AIRPORT"] = weather_data["NAME"].str.split(",").str[0]
weather_data.head()

,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,WSF5,PRCP,SNOW,TAVG,TMAX,TMIN,AIRPORT,LOCATION
0,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-01,7.8,40.0,4.99,2.8,41.8,46.2,37.3,SEATTLE TACOMA AIRPORT,WA US
1,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-02,8.7,46.0,3.06,2.0,39.3,45.0,33.5,SEATTLE TACOMA AIRPORT,WA US
2,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-03,9.8,55.0,6.29,0.0,45.2,51.4,38.9,SEATTLE TACOMA AIRPORT,WA US
3,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-04,8.5,36.0,4.47,0.0,45.5,52.2,38.8,SEATTLE TACOMA AIRPORT,WA US
4,"SEATTLE TACOMA AIRPORT, WA US",47.44467,-122.31442,112.5,2011-05,7.2,32.0,3.20,0.0,52.3,59.7,44.9,SEATTLE TACOMA AIRPORT,WA US

In [12]:
#Change 'Name' elements into their respective Airport Abbreviations

weather_data["NAME"].replace({"SEATTLE TACOMA AIRPORT, WA US":"SEA",
                              "FORT LAUDERDALE INTERNATIONAL AIRPORT, FL US": "FLL",
                              "LONG BEACH DAUGHERTY AIRPORT, CA US":"LGB",
                              "MCCARRAN INTERNATIONAL AIRPORT, NV US":"LAS",
                              "LAGUARDIA AIRPORT, NY US":"LGA",
                              "NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US":"EWR",
                              "ORLANDO SANFORD AIRPORT, FL US":"SFB",
                              "DAL FTW WSCMO AIRPORT, TX US":"DFW",
                              "BALTIMORE WASHINGTON INTERNATIONAL AIRPORT, MD US":"BWI",
                              "WASHINGTON REAGAN NATIONAL AIRPORT, VA US":"DCA",
                              "DALLAS FAA AIRPORT, TX US":"DAL",
                              "LOS ANGELES INTERNATIONAL AIRPORT, CA US":"LAX",
                              "EVERETT SNOHOMISH CO AIRPORT, WA US":"PAE",
                              "SANTA ANA JOHN WAYNE AIRPORT, CA US":"SNA",
                              "MIAMI INTERNATIONAL AIRPORT, FL US":"MIA",
                              "ORLANDO INTERNATIONAL AIRPORT, FL US":"MCO",
                              "BOSTON, MA US":"BOS",
                              "SAN FRANCISCO INTERNATIONAL AIRPORT, CA US":"SFO",
                              "CHICAGO MIDWAY AIRPORT, IL US":"ORD",
                              "ONTARIO INTERNATIONAL AIRPORT, CA US":"ONT",
                              "WASHINGTON DULLES INTERNATIONAL AIRPORT, VA US":"IAD",
                              "PROVIDENCE, RI US":"PVD",
                              "JFK INTERNATIONAL AIRPORT, NY US":"JFK",
                              "ATLANTA HARTSFIELD JACKSON INTERNATIONAL AIRPORT, GA US":"ATL",
                              "CHICAGO OHARE INTERNATIONAL AIRPORT, IL US":"ORD"
                             }, inplace = True)
weather_data.head()

,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,WSF5,PRCP,SNOW,TAVG,TMAX,TMIN,AIRPORT,LOCATION
0,SEA,47.44467,-122.31442,112.5,2011-01,7.8,40.0,4.99,2.8,41.8,46.2,37.3,SEATTLE TACOMA AIRPORT,WA US
1,SEA,47.44467,-122.31442,112.5,2011-02,8.7,46.0,3.06,2.0,39.3,45.0,33.5,SEATTLE TACOMA AIRPORT,WA US
2,SEA,47.44467,-122.31442,112.5,2011-03,9.8,55.0,6.29,0.0,45.2,51.4,38.9,SEATTLE TACOMA AIRPORT,WA US
3,SEA,47.44467,-122.31442,112.5,2011-04,8.5,36.0,4.47,0.0,45.5,52.2,38.8,SEATTLE TACOMA AIRPORT,WA US
4,SEA,47.44467,-122.31442,112.5,2011-05,7.2,32.0,3.20,0.0,52.3,59.7,44.9,SEATTLE TACOMA AIRPORT,WA US

In [13]:
#Rename 'Name' column to 'Airport Code'

weather_data.rename(columns={"NAME": "AIRPORT CODE"}, inplace=True)
weather_data.head()

,AIRPORT CODE,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,WSF5,PRCP,SNOW,TAVG,TMAX,TMIN,AIRPORT,LOCATION
0,SEA,47.44467,-122.31442,112.5,2011-01,7.8,40.0,4.99,2.8,41.8,46.2,37.3,SEATTLE TACOMA AIRPORT,WA US
1,SEA,47.44467,-122.31442,112.5,2011-02,8.7,46.0,3.06,2.0,39.3,45.0,33.5,SEATTLE TACOMA AIRPORT,WA US
2,SEA,47.44467,-122.31442,112.5,2011-03,9.8,55.0,6.29,0.0,45.2,51.4,38.9,SEATTLE TACOMA AIRPORT,WA US
3,SEA,47.44467,-122.31442,112.5,2011-04,8.5,36.0,4.47,0.0,45.5,52.2,38.8,SEATTLE TACOMA AIRPORT,WA US
4,SEA,47.44467,-122.31442,112.5,2011-05,7.2,32.0,3.20,0.0,52.3,59.7,44.9,SEATTLE TACOMA AIRPORT,WA US

In [14]:
#Rearranging Columns 

weather_data = weather_data[["AIRPORT CODE", "AIRPORT", "LATITUDE", "LONGITUDE", "ELEVATION", "DATE",
                            "AWND", "WSF5", "PRCP", "SNOW", "TAVG", "TMAX", "TMIN"]]
weather_data.head()

,AIRPORT CODE,AIRPORT,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,WSF5,PRCP,SNOW,TAVG,TMAX,TMIN
0,SEA,SEATTLE TACOMA AIRPORT,47.44467,-122.31442,112.5,2011-01,7.8,40.0,4.99,2.8,41.8,46.2,37.3
1,SEA,SEATTLE TACOMA AIRPORT,47.44467,-122.31442,112.5,2011-02,8.7,46.0,3.06,2.0,39.3,45.0,33.5
2,SEA,SEATTLE TACOMA AIRPORT,47.44467,-122.31442,112.5,2011-03,9.8,55.0,6.29,0.0,45.2,51.4,38.9
3,SEA,SEATTLE TACOMA AIRPORT,47.44467,-122.31442,112.5,2011-04,8.5,36.0,4.47,0.0,45.5,52.2,38.8
4,SEA,SEATTLE TACOMA AIRPORT,47.44467,-122.31442,112.5,2011-05,7.2,32.0,3.20,0.0,52.3,59.7,44.9

In [15]:
#Chaning Column Names

weather_data.rename(columns={"AWND":"Average Wind Speed", "WSF5":"Max Gust Speed",
                                "PRCP":"Precipitation", "SNOW": "Snow Accumulation",
                                "TAVG":"Average Temperature", "TMAX":"Max Temperature",
                                 "TMIN":"Min Temperature"}, inplace=True)
weather_data.head()

C:\Users\lshrn\anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,AIRPORT CODE,AIRPORT,LATITUDE,LONGITUDE,ELEVATION,DATE,Average Wind Speed,Max Gust Speed,Precipitation,Snow Accumulation,Average Temperature,Max Temperature,Min Temperature
0,SEA,SEATTLE TACOMA AIRPORT,47.44467,-122.31442,112.5,2011-01,7.8,40.0,4.99,2.8,41.8,46.2,37.3
1,SEA,SEATTLE TACOMA AIRPORT,47.44467,-122.31442,112.5,2011-02,8.7,46.0,3.06,2.0,39.3,45.0,33.5
2,SEA,SEATTLE TACOMA AIRPORT,47.44467,-122.31442,112.5,2011-03,9.8,55.0,6.29,0.0,45.2,51.4,38.9
3,SEA,SEATTLE TACOMA AIRPORT,47.44467,-122.31442,112.5,2011-04,8.5,36.0,4.47,0.0,45.5,52.2,38.8
4,SEA,SEATTLE TACOMA AIRPORT,47.44467,-122.31442,112.5,2011-05,7.2,32.0,3.20,0.0,52.3,59.7,44.9

In [16]:
#Dataframe showing averages of columns

monthly_summary = weather_data.groupby(["DATE", "AIRPORT CODE", "LATITUDE", "LONGITUDE", "ELEVATION"]).mean()
monthly_summary.head()

                                                   Average Wind Speed  \
DATE    AIRPORT CODE LATITUDE LONGITUDE ELEVATION
2011-01 ATL          33.62972 -84.44224 308.2                     8.9
        BOS          42.36057 -71.00975 3.2                      10.7
        BWI          39.17329 -76.68408 42.0                      6.3
        DAL          32.83839 -96.83583 147.6                     6.9
        DCA          38.84721 -77.03454 4.1                       8.5

                                                   Max Gust Speed  \
DATE    AIRPORT CODE LATITUDE LONGITUDE ELEVATION
2011-01 ATL          33.62972 -84.44224 308.2                41.0
        BOS          42.36057 -71.00975 3.2                  46.0
        BWI          39.17329 -76.68408 42.0                 40.0
        DAL          32.83839 -96.83583 147.6                38.0
        DCA          38.84721 -77.03454 4.1                  41.0

                                                   Precipitation  \
DATE    AIRPORT CODE LATITUDE LONGITUDE ELEVATION
2011-01 ATL          33.62972 -84.44224 308.2               2.63
        BOS          42.36057 -71.00975 3.2                 4.57
        BWI          39.17329 -76.68408 42.0                2.67
        DAL          32.83839 -96.83583 147.6               1.62
        DCA          38.84721 -77.03454 4.1                 2.25

                                                   Snow Accumulation  \
DATE    AIRPORT CODE LATITUDE LONGITUDE ELEVATION
2011-01 ATL          33.62972 -84.44224 308.2                    4.4
        BOS          42.36057 -71.00975 3.2                     38.3
        BWI          39.17329 -76.68408 42.0                    10.7
        DAL          32.83839 -96.83583 147.6                    0.1
        DCA          38.84721 -77.03454 4.1                      7.3

                                                   Average Temperature  \
DATE    AIRPORT CODE LATITUDE LONGITUDE ELEVATION
2011-01 ATL          33.62972 -84.44224 308.2                     40.2
        BOS          42.36057 -71.00975 3.2                       27.6
        BWI          39.17329 -76.68408 42.0                      30.2
        DAL          32.83839 -96.83583 147.6                     43.8
        DCA          38.84721 -77.03454 4.1                       33.7

                                                   Max Temperature  \
DATE    AIRPORT CODE LATITUDE LONGITUDE ELEVATION
2011-01 ATL          33.62972 -84.44224 308.2                 48.5
        BOS          42.36057 -71.00975 3.2                   33.6
        BWI          39.17329 -76.68408 42.0                  37.8
        DAL          32.83839 -96.83583 147.6                 53.7
        DCA          38.84721 -77.03454 4.1                   39.7

                                                   Min Temperature
DATE    AIRPORT CODE LATITUDE LONGITUDE ELEVATION
2011-01 ATL          33.62972 -84.44224 308.2                 31.8
        BOS          42.36057 -71.00975 3.2                   21.6
        BWI          39.17329 -76.68408 42.0                  22.7
        DAL          32.83839 -96.83583 147.6                 33.8
        DCA          38.84721 -77.03454 4.1                   27.6